import pytest
from datetime import datetime, timezone
from backend.app.schemas.analysis import AnalysisRequest, StructuredPlan
from backend.app.schemas.weather import WeatherCondition, GeoLocation, DailyForecast
from backend.app.orchestration.state import WorkflowState
from backend.app.orchestration.workflow import pipeline, WeatherIntelligencePipeline
from backend.app.agents.planner import PlannerAgent
from backend.app.agents.data_agent import DataAgent
from backend.app.agents.risk_analyst import RiskAnalysisAgent
from backend.app.agents.recommendation import RecommendationAgent
from backend.app.agents.critic import CriticAgent
from backend.app.monitoring.tracer import AgentExecutionTracer


# ============================================================================
# 1. APPROVAL PATH (Happy Path Full Multi-Agent Workflow)
# ============================================================================

@pytest.mark.asyncio
async def test_multi_agent_approval_path():
    """Approval path: All 5 agents execute, Critic validates and issues APPROVE."""
    req = AnalysisRequest(
        query="Can I plan a high altitude mountain trek tomorrow?",
        location="Shimla",
        target_date="2026-09-27"
    )

    response = await pipeline.run(req)

    # 1. Assert Plan generated by PlannerAgent
    assert response.plan is not None
    assert isinstance(response.plan, StructuredPlan)
    assert "Hiking" in response.plan.entities.get("activity_category", "")
    assert len(response.plan.sub_goals) >= 4
    assert "max_rain_probability" in response.plan.constraints

    # 2. Assert Real Telemetry from DataAgent
    assert response.weather is not None
    assert response.weather.source == "open-meteo-live"
    assert response.weather.temp_c is not None

    # 3. Assert Recommendation from RecommendationAgent
    assert len(response.recommendation.options_comparison) >= 2
    assert len(response.recommendation.evidence_citations) >= 3
    assert len(response.recommendation.stated_limitations) >= 3

    # 4. Assert Critic Review produced APPROVE
    assert len(response.critic_reviews) >= 1
    final_review = response.critic_reviews[-1]
    assert final_review.verdict == "APPROVE"
    assert final_review.critique_score >= 70
    assert final_review.hallucination_free is True
    assert final_review.data_consistency_passed is True

    # 5. Assert Audit Trace logs action, reasoning, and duration for all steps
    assert len(response.trace) >= 5
    for step in response.trace:
        assert step.action is not None and len(step.action) > 0
        assert step.reasoning is not None and len(step.reasoning) > 0
        assert step.duration_ms >= 0.0

    # 6. Assert Stopping Condition
    assert response.stopping_condition.reviews_count <= 2
    assert response.stopping_condition.stopped_early is False


# ============================================================================
# 2. REJECTION PATH (Flawed Recommendation Triggers Critic REJECT & Correction)
# ============================================================================

@pytest.mark.asyncio
async def test_critic_rejection_and_correction_cycle():
    """Rejection path: Over-optimistic verdict triggers Critic REJECT with actionable correction."""
    tracer = AgentExecutionTracer()

    # Create mock weather with dangerous rain and wind
    bad_weather = WeatherCondition(
        location=GeoLocation(name="AlpinePass", latitude=32.0, longitude=77.0),
        observed_date="2026-09-27",
        temp_c=6.0,
        feels_like_c=3.0,
        humidity=95,
        wind_kph=38.0,
        wind_direction="NW",
        condition_text="Heavy Rain Showers",
        precipitation_mm=12.0,
        precipitation_prob=85,
        uv_index=3.0,
        forecast_days=[
            DailyForecast(
                date="2026-09-27",
                max_temp_c=8.0,
                min_temp_c=2.0,
                avg_temp_c=5.0,
                condition="Heavy Rain",
                rain_probability=85,
                uv_index=3.0,
                wind_max_kph=38.0
            )
        ],
        source="open-meteo-live"
    )

    state = WorkflowState(
        query="High alpine ridge traverse",
        location_name="AlpinePass",
        target_date="2026-09-27",
        weather=bad_weather,
        outdoor_score=35,
        # Flawed recommendation: claiming "Optimal" despite 85% rain and 38 km/h winds!
        verdict_badge="Optimal",
        headline="Clear skies recommended",
        stated_limitations=["Mountain weather varies"],
    )

    # Initialize plan constraints
    planner = PlannerAgent()
    state = await planner.process(state, tracer)
    # Manually re-assert flawed verdict to test Critic detection
    state.verdict_badge = "Optimal"

    critic = CriticAgent()
    state = await critic.process(state, tracer)

    # Assert Critic caught the contradiction and REJECTED
    first_review = state.current_critic_review
    assert first_review.verdict == "REJECT"
    assert first_review.critique_score < 60
    assert first_review.data_consistency_passed is False
    assert first_review.correction_request is not None
    assert "85%" in first_review.correction_request or "exceeding" in first_review.correction_request

    # Now simulate RecommendationAgent receiving this correction request
    recommender = RecommendationAgent()
    state = await recommender.process(state, tracer)

    # Assert RecommendationAgent revised the verdict upon correction
    assert state.verdict_badge in ["Caution", "Unfavorable"]
    assert "Revised after Critic" in state.comfort_summary or "Caution" in state.verdict_badge

    # Now Critic audits the revised recommendation
    state = await critic.process(state, tracer)
    second_review = state.current_critic_review
    assert second_review.verdict == "APPROVE"
    assert second_review.critique_score > first_review.critique_score


# ============================================================================
# 3. INSUFFICIENT DATA PATH (NEEDS_MORE_DATA)
# ============================================================================

@pytest.mark.asyncio
async def test_critic_insufficient_data_path():
    """Insufficient data path: Incomplete telemetry triggers NEEDS_MORE_DATA and stops gracefully."""
    tracer = AgentExecutionTracer()

    # Weather with missing critical fields (no forecast days)
    partial_weather = WeatherCondition(
        location=GeoLocation(name="RemoteOutpost", latitude=35.0, longitude=75.0),
        observed_date="2026-09-27",
        temp_c=15.0,
        feels_like_c=14.0,
        humidity=50,
        wind_kph=10.0,
        wind_direction="N",
        condition_text="Clear",
        precipitation_mm=0.0,
        precipitation_prob=10,
        uv_index=4.0,
        forecast_days=[],  # Empty forecast days!
        source="open-meteo-live"
    )

    state = WorkflowState(
        query="Camping trip",
        location_name="RemoteOutpost",
        target_date="2026-09-27",
        weather=partial_weather,
    )

    critic = CriticAgent()
    state = await critic.process(state, tracer)

    review = state.current_critic_review
    assert review.verdict == "NEEDS_MORE_DATA"
    assert review.critique_score <= 30
    assert "Critical meteorological telemetry missing" in review.critique_notes


# ============================================================================
# 4. REVIEW CAPPING & BUDGET STOPPING CONDITION
# ============================================================================

@pytest.mark.asyncio
async def test_orchestrator_review_capping_at_two():
    """Stopping condition: Review attempts capped at maximum limit (2 iterations)."""
    orchestrator = WeatherIntelligencePipeline()

    # Force Critic to always reject to verify capping at 2
    class AlwaysRejectCritic(CriticAgent):
        async def process(self, state, tracer):
            iteration = len(state.critic_reviews) + 1
            from backend.app.schemas.analysis import CriticReview
            review = CriticReview(
                verdict="REJECT",
                critique_score=40,
                data_consistency_passed=False,
                constraints_satisfied=False,
                hallucination_free=True,
                critique_notes="Perpetual contradiction test",
                correction_request="Revise again",
                iteration=iteration,
                timestamp="2026-09-27T00:00:00Z"
            )
            state.critic_reviews.append(review)
            state.current_critic_review = review
            state.active_correction_request = review.correction_request
            return state

    orchestrator.critic = AlwaysRejectCritic()

    req = AnalysisRequest(
        query="Hiking expedition",
        location="Delhi",
        target_date="2026-09-27"
    )

    res = await orchestrator.run(req)

    # Verify review count was strictly capped at 2
    assert res.stopping_condition.reviews_count == 2
    assert res.stopping_condition.stopped_early is True
    assert "capped at maximum limit (2 iterations)" in res.stopping_condition.reason
