from typing import List, Optional, Dict, Any
from pydantic import BaseModel, Field
from .weather import WeatherCondition


class AnalysisRequest(BaseModel):
    query: str = Field(..., description="User query or planned activity (e.g., 'Can I go hiking?', 'Outdoor wedding planning')")
    location: str = Field(..., description="Target city or location name (e.g., 'Shimla', 'San Francisco')")
    target_date: Optional[str] = Field(default=None, description="Target date in YYYY-MM-DD format. Defaults to today/tomorrow.")


class StructuredPlan(BaseModel):
    """Generated by PlannerAgent: structured interpretation of intent, entities, and constraints."""
    entities: Dict[str, Any] = Field(default_factory=dict, description="Parsed entities: activity, location, window, gear focus")
    sub_goals: List[str] = Field(default_factory=list, description="Ordered sub-goals to execute")
    constraints: Dict[str, Any] = Field(default_factory=dict, description="Configured constraints (max rain %, max wind, temp boundaries)")


class RuleEvaluation(BaseModel):
    """Individual transparent rule evaluation from RiskAnalysisAgent."""
    rule_id: str
    description: str
    condition_evaluated: str
    triggered: bool
    severity: str  # "none", "low", "moderate", "high", "critical"
    penalty: int
    mitigation: str


class RiskAssessmentResult(BaseModel):
    """Aggregate output from RiskAnalysisAgent."""
    outdoor_score: int
    risk_level: str  # "Low", "Moderate", "High", "Critical"
    summary: str
    rules_evaluated: List[RuleEvaluation] = Field(default_factory=list)


class OptionComparison(BaseModel):
    """Comparative analysis generated by RecommendationAgent."""
    option_name: str
    suitability_score: int
    verdict: str  # "Optimal", "Viable", "Suboptimal", "Sheltered Backup"
    pros: List[str] = Field(default_factory=list)
    cons: List[str] = Field(default_factory=list)


class EvidenceCitation(BaseModel):
    """Explicitly cited empirical meteorological measurement grounding the decision."""
    metric: str
    observed_value: str
    implication: str


class CriticReview(BaseModel):
    """Validation output produced by CriticAgent."""
    verdict: str  # "APPROVE", "REJECT", "NEEDS_MORE_DATA"
    critique_score: int = Field(default=100, description="0 to 100 critique validation confidence")
    data_consistency_passed: bool
    constraints_satisfied: bool
    hallucination_free: bool
    critique_notes: str
    correction_request: Optional[str] = None
    iteration: int = 1
    timestamp: str


class AgentTraceStep(BaseModel):
    """Audit trace item logging each agent's action, input, output, and explicit reasoning."""
    id: str
    agent_name: str
    stage: str
    action: str = Field(default="EXECUTE", description="Action performed by agent")
    reasoning: str = Field(default="", description="Explicit chain-of-thought or heuristic justification")
    status: str  # "completed", "running", "failed"
    duration_ms: float
    timestamp: str
    summary: str
    inputs: Dict[str, Any] = Field(default_factory=dict)
    outputs: Dict[str, Any] = Field(default_factory=dict)


class RiskItem(BaseModel):
    severity: str  # "low", "moderate", "high", "critical"
    title: str
    description: str
    mitigation: str


class ActivityRecommendation(BaseModel):
    activity: str
    verdict: str  # "Recommended", "Conditional", "Not Recommended"
    confidence_score: int  # 0 to 100
    reasoning: str
    ideal_time_window: str
    gear_required: List[str] = Field(default_factory=list)
    alternatives: List[str] = Field(default_factory=list)


class RecommendationCard(BaseModel):
    headline: str
    verdict_badge: str  # "Optimal", "Caution", "Unfavorable", "Severe"
    outdoor_score: int  # 0-100
    comfort_summary: str
    activities: List[ActivityRecommendation] = Field(default_factory=list)
    options_comparison: List[OptionComparison] = Field(default_factory=list)
    evidence_citations: List[EvidenceCitation] = Field(default_factory=list)
    stated_limitations: List[str] = Field(default_factory=list)
    packing_checklist: List[str] = Field(default_factory=list)
    risk_alerts: List[RiskItem] = Field(default_factory=list)
    critic_review: Optional[CriticReview] = None


class StoppingCondition(BaseModel):
    """Enforces orchestration constraints and budget accountability."""
    stopped_early: bool = False
    reason: str = "Pipeline completed normal execution"
    reviews_count: int = 1
    max_reviews: int = 2
    steps_executed: int = 5
    max_steps: int = 10
    duration_ms: float = 0.0
    time_budget_ms: float = 15000.0
    estimated_cost_usd: float = 0.001


class AnalysisResponse(BaseModel):
    query: str
    location: str
    target_date: str
    plan: Optional[StructuredPlan] = None
    weather: WeatherCondition
    recommendation: RecommendationCard
    critic_reviews: List[CriticReview] = Field(default_factory=list)
    trace: List[AgentTraceStep] = Field(default_factory=list)
    stopping_condition: StoppingCondition
    total_execution_ms: float
    generated_at: str
